export const CREATE_SESSION_REQUEST = "tti_admin/CREATE_SESSION_REQUEST";
export const CREATE_SESSION_SUCCESS = "tti_admin/CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_ERROR = "tti_admin/CREATE_SESSION_ERROR";
