export const FETCH_SESSION_REQUEST = "tti_admin/FETCH_SESSION_REQUEST";
export const FETCH_SESSION_SUCCESS = "tti_admin/FETCH_SESSION_SUCCESS";
export const FETCH_SESSION_ERROR = "tti_admin/FETCH_SESSION_ERROR";
