export const ADD_EMPLOYEE_REQUEST = "tti_admin/ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "tti_admin/ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR = "tti_admin/ADD_EMPLOYEE_ERROR";

export const FETCH_EMPLOYEES_REQUEST = "tti_admin/FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESS = "tti_admin/FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_ERROR = "tti_admin/FETCH_EMPLOYEES_ERROR";

export const DELETE_EMPLOYEE_REQUEST = "tti_admin/DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "tti_admin/DELETE_EMPLOYEE_SUCCES";
export const DELETE_EMPLOYEE_ERROR = "tti_admin/DELETE_EMPLOYEE_ERROR";

export const FETCH_EMPLOYEE_REQUEST = "tti_admin/FETCH_EMPLOYEE_REQUEST";
export const FETCH_EMPLOYEE_SUCCESS = "tti_admin/FETCH_EMPLOYEE_SUCCES";
export const FETCH_EMPLOYEE_ERROR = "tti_admin/FETCH_EMPLOYEE_ERROR";

export const EDIT_EMPLOYEE_REQUEST = "tti_admin/EDIT_EMPLOYEE_REQUEST";
export const EDIT_EMPLOYEE_SUCCESS = "tti_admin/EDIT_EMPLOYEE_SUCCES";
export const EDIT_EMPLOYEE_ERROR = "tti_admin/EDIT_EMPLOYEE_ERROR";
